# Generated by Django 3.2.3 on 2023-08-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230818_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='navigate',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
